// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewBorrowerRepository creates a new instance of BorrowerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBorrowerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BorrowerRepository {
	mock := &BorrowerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BorrowerRepository is an autogenerated mock type for the BorrowerRepository type
type BorrowerRepository struct {
	mock.Mock
}

type BorrowerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BorrowerRepository) EXPECT() *BorrowerRepository_Expecter {
	return &BorrowerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type BorrowerRepository
func (_mock *BorrowerRepository) Create(ctx context.Context, borrower *models.Borrower) error {
	ret := _mock.Called(ctx, borrower)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Borrower) error); ok {
		r0 = returnFunc(ctx, borrower)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BorrowerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BorrowerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - borrower *models.Borrower
func (_e *BorrowerRepository_Expecter) Create(ctx interface{}, borrower interface{}) *BorrowerRepository_Create_Call {
	return &BorrowerRepository_Create_Call{Call: _e.mock.On("Create", ctx, borrower)}
}

func (_c *BorrowerRepository_Create_Call) Run(run func(ctx context.Context, borrower *models.Borrower)) *BorrowerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Borrower
		if args[1] != nil {
			arg1 = args[1].(*models.Borrower)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerRepository_Create_Call) Return(err error) *BorrowerRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BorrowerRepository_Create_Call) RunAndReturn(run func(ctx context.Context, borrower *models.Borrower) error) *BorrowerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type BorrowerRepository
func (_mock *BorrowerRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BorrowerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BorrowerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *BorrowerRepository_Expecter) Delete(ctx interface{}, id interface{}) *BorrowerRepository_Delete_Call {
	return &BorrowerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *BorrowerRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *BorrowerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerRepository_Delete_Call) Return(err error) *BorrowerRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BorrowerRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *BorrowerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByBorrowerIDNumber provides a mock function for the type BorrowerRepository
func (_mock *BorrowerRepository) GetByBorrowerIDNumber(ctx context.Context, borrowerIDNumber string) (*models.Borrower, error) {
	ret := _mock.Called(ctx, borrowerIDNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByBorrowerIDNumber")
	}

	var r0 *models.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Borrower, error)); ok {
		return returnFunc(ctx, borrowerIDNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Borrower); ok {
		r0 = returnFunc(ctx, borrowerIDNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, borrowerIDNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BorrowerRepository_GetByBorrowerIDNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBorrowerIDNumber'
type BorrowerRepository_GetByBorrowerIDNumber_Call struct {
	*mock.Call
}

// GetByBorrowerIDNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - borrowerIDNumber string
func (_e *BorrowerRepository_Expecter) GetByBorrowerIDNumber(ctx interface{}, borrowerIDNumber interface{}) *BorrowerRepository_GetByBorrowerIDNumber_Call {
	return &BorrowerRepository_GetByBorrowerIDNumber_Call{Call: _e.mock.On("GetByBorrowerIDNumber", ctx, borrowerIDNumber)}
}

func (_c *BorrowerRepository_GetByBorrowerIDNumber_Call) Run(run func(ctx context.Context, borrowerIDNumber string)) *BorrowerRepository_GetByBorrowerIDNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerRepository_GetByBorrowerIDNumber_Call) Return(borrower *models.Borrower, err error) *BorrowerRepository_GetByBorrowerIDNumber_Call {
	_c.Call.Return(borrower, err)
	return _c
}

func (_c *BorrowerRepository_GetByBorrowerIDNumber_Call) RunAndReturn(run func(ctx context.Context, borrowerIDNumber string) (*models.Borrower, error)) *BorrowerRepository_GetByBorrowerIDNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type BorrowerRepository
func (_mock *BorrowerRepository) GetByID(ctx context.Context, id int) (*models.Borrower, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Borrower, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Borrower); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BorrowerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type BorrowerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *BorrowerRepository_Expecter) GetByID(ctx interface{}, id interface{}) *BorrowerRepository_GetByID_Call {
	return &BorrowerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *BorrowerRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *BorrowerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerRepository_GetByID_Call) Return(borrower *models.Borrower, err error) *BorrowerRepository_GetByID_Call {
	_c.Call.Return(borrower, err)
	return _c
}

func (_c *BorrowerRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Borrower, error)) *BorrowerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type BorrowerRepository
func (_mock *BorrowerRepository) List(ctx context.Context, offset int, limit int) ([]*models.Borrower, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Borrower, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*models.Borrower); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BorrowerRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type BorrowerRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *BorrowerRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *BorrowerRepository_List_Call {
	return &BorrowerRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *BorrowerRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *BorrowerRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BorrowerRepository_List_Call) Return(borrowers []*models.Borrower, err error) *BorrowerRepository_List_Call {
	_c.Call.Return(borrowers, err)
	return _c
}

func (_c *BorrowerRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*models.Borrower, error)) *BorrowerRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type BorrowerRepository
func (_mock *BorrowerRepository) Update(ctx context.Context, borrower *models.Borrower) error {
	ret := _mock.Called(ctx, borrower)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Borrower) error); ok {
		r0 = returnFunc(ctx, borrower)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BorrowerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BorrowerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - borrower *models.Borrower
func (_e *BorrowerRepository_Expecter) Update(ctx interface{}, borrower interface{}) *BorrowerRepository_Update_Call {
	return &BorrowerRepository_Update_Call{Call: _e.mock.On("Update", ctx, borrower)}
}

func (_c *BorrowerRepository_Update_Call) Run(run func(ctx context.Context, borrower *models.Borrower)) *BorrowerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Borrower
		if args[1] != nil {
			arg1 = args[1].(*models.Borrower)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerRepository_Update_Call) Return(err error) *BorrowerRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BorrowerRepository_Update_Call) RunAndReturn(run func(ctx context.Context, borrower *models.Borrower) error) *BorrowerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
