// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"database/sql"

	"github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
)

// NewDriver creates a new instance of Driver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Driver {
	mock := &Driver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Driver is an autogenerated mock type for the Driver type
type Driver struct {
	mock.Mock
}

type Driver_Expecter struct {
	mock *mock.Mock
}

func (_m *Driver) EXPECT() *Driver_Expecter {
	return &Driver_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Driver
func (_mock *Driver) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Driver_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Driver_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Driver_Expecter) Close() *Driver_Close_Call {
	return &Driver_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Driver_Close_Call) Run(run func()) *Driver_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Driver_Close_Call) Return(err error) *Driver_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Driver_Close_Call) RunAndReturn(run func() error) *Driver_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function for the type Driver
func (_mock *Driver) GetDB() *sql.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *sql.DB
	if returnFunc, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}
	return r0
}

// Driver_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type Driver_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
func (_e *Driver_Expecter) GetDB() *Driver_GetDB_Call {
	return &Driver_GetDB_Call{Call: _e.mock.On("GetDB")}
}

func (_c *Driver_GetDB_Call) Run(run func()) *Driver_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Driver_GetDB_Call) Return(dB *sql.DB) *Driver_GetDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *Driver_GetDB_Call) RunAndReturn(run func() *sql.DB) *Driver_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// GetUtilDB provides a mock function for the type Driver
func (_mock *Driver) GetUtilDB() *sqlx.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUtilDB")
	}

	var r0 *sqlx.DB
	if returnFunc, ok := ret.Get(0).(func() *sqlx.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.DB)
		}
	}
	return r0
}

// Driver_GetUtilDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUtilDB'
type Driver_GetUtilDB_Call struct {
	*mock.Call
}

// GetUtilDB is a helper method to define mock.On call
func (_e *Driver_Expecter) GetUtilDB() *Driver_GetUtilDB_Call {
	return &Driver_GetUtilDB_Call{Call: _e.mock.On("GetUtilDB")}
}

func (_c *Driver_GetUtilDB_Call) Run(run func()) *Driver_GetUtilDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Driver_GetUtilDB_Call) Return(dB *sqlx.DB) *Driver_GetUtilDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *Driver_GetUtilDB_Call) RunAndReturn(run func() *sqlx.DB) *Driver_GetUtilDB_Call {
	_c.Call.Return(run)
	return _c
}
