// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewInvestorRepository creates a new instance of InvestorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvestorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvestorRepository {
	mock := &InvestorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InvestorRepository is an autogenerated mock type for the InvestorRepository type
type InvestorRepository struct {
	mock.Mock
}

type InvestorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvestorRepository) EXPECT() *InvestorRepository_Expecter {
	return &InvestorRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type InvestorRepository
func (_mock *InvestorRepository) Create(ctx context.Context, investor *models.Investor) error {
	ret := _mock.Called(ctx, investor)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Investor) error); ok {
		r0 = returnFunc(ctx, investor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvestorRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InvestorRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - investor *models.Investor
func (_e *InvestorRepository_Expecter) Create(ctx interface{}, investor interface{}) *InvestorRepository_Create_Call {
	return &InvestorRepository_Create_Call{Call: _e.mock.On("Create", ctx, investor)}
}

func (_c *InvestorRepository_Create_Call) Run(run func(ctx context.Context, investor *models.Investor)) *InvestorRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Investor
		if args[1] != nil {
			arg1 = args[1].(*models.Investor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorRepository_Create_Call) Return(err error) *InvestorRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvestorRepository_Create_Call) RunAndReturn(run func(ctx context.Context, investor *models.Investor) error) *InvestorRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type InvestorRepository
func (_mock *InvestorRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvestorRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type InvestorRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *InvestorRepository_Expecter) Delete(ctx interface{}, id interface{}) *InvestorRepository_Delete_Call {
	return &InvestorRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *InvestorRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *InvestorRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorRepository_Delete_Call) Return(err error) *InvestorRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvestorRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *InvestorRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type InvestorRepository
func (_mock *InvestorRepository) GetByEmail(ctx context.Context, email string) (*models.Investor, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.Investor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Investor, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Investor); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Investor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvestorRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type InvestorRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *InvestorRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *InvestorRepository_GetByEmail_Call {
	return &InvestorRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *InvestorRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *InvestorRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorRepository_GetByEmail_Call) Return(investor *models.Investor, err error) *InvestorRepository_GetByEmail_Call {
	_c.Call.Return(investor, err)
	return _c
}

func (_c *InvestorRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.Investor, error)) *InvestorRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type InvestorRepository
func (_mock *InvestorRepository) GetByID(ctx context.Context, id int) (*models.Investor, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Investor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Investor, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Investor); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Investor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvestorRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type InvestorRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *InvestorRepository_Expecter) GetByID(ctx interface{}, id interface{}) *InvestorRepository_GetByID_Call {
	return &InvestorRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *InvestorRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *InvestorRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorRepository_GetByID_Call) Return(investor *models.Investor, err error) *InvestorRepository_GetByID_Call {
	_c.Call.Return(investor, err)
	return _c
}

func (_c *InvestorRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Investor, error)) *InvestorRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByInvestorID provides a mock function for the type InvestorRepository
func (_mock *InvestorRepository) GetByInvestorID(ctx context.Context, investorID string) (*models.Investor, error) {
	ret := _mock.Called(ctx, investorID)

	if len(ret) == 0 {
		panic("no return value specified for GetByInvestorID")
	}

	var r0 *models.Investor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Investor, error)); ok {
		return returnFunc(ctx, investorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Investor); ok {
		r0 = returnFunc(ctx, investorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Investor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, investorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvestorRepository_GetByInvestorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByInvestorID'
type InvestorRepository_GetByInvestorID_Call struct {
	*mock.Call
}

// GetByInvestorID is a helper method to define mock.On call
//   - ctx context.Context
//   - investorID string
func (_e *InvestorRepository_Expecter) GetByInvestorID(ctx interface{}, investorID interface{}) *InvestorRepository_GetByInvestorID_Call {
	return &InvestorRepository_GetByInvestorID_Call{Call: _e.mock.On("GetByInvestorID", ctx, investorID)}
}

func (_c *InvestorRepository_GetByInvestorID_Call) Run(run func(ctx context.Context, investorID string)) *InvestorRepository_GetByInvestorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorRepository_GetByInvestorID_Call) Return(investor *models.Investor, err error) *InvestorRepository_GetByInvestorID_Call {
	_c.Call.Return(investor, err)
	return _c
}

func (_c *InvestorRepository_GetByInvestorID_Call) RunAndReturn(run func(ctx context.Context, investorID string) (*models.Investor, error)) *InvestorRepository_GetByInvestorID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type InvestorRepository
func (_mock *InvestorRepository) List(ctx context.Context, offset int, limit int) ([]*models.Investor, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Investor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Investor, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*models.Investor); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Investor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvestorRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InvestorRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *InvestorRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *InvestorRepository_List_Call {
	return &InvestorRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *InvestorRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *InvestorRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InvestorRepository_List_Call) Return(investors []*models.Investor, err error) *InvestorRepository_List_Call {
	_c.Call.Return(investors, err)
	return _c
}

func (_c *InvestorRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*models.Investor, error)) *InvestorRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type InvestorRepository
func (_mock *InvestorRepository) Update(ctx context.Context, investor *models.Investor) error {
	ret := _mock.Called(ctx, investor)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Investor) error); ok {
		r0 = returnFunc(ctx, investor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvestorRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type InvestorRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - investor *models.Investor
func (_e *InvestorRepository_Expecter) Update(ctx interface{}, investor interface{}) *InvestorRepository_Update_Call {
	return &InvestorRepository_Update_Call{Call: _e.mock.On("Update", ctx, investor)}
}

func (_c *InvestorRepository_Update_Call) Run(run func(ctx context.Context, investor *models.Investor)) *InvestorRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Investor
		if args[1] != nil {
			arg1 = args[1].(*models.Investor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorRepository_Update_Call) Return(err error) *InvestorRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvestorRepository_Update_Call) RunAndReturn(run func(ctx context.Context, investor *models.Investor) error) *InvestorRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
