// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewLoanApprovalRepository creates a new instance of LoanApprovalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanApprovalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanApprovalRepository {
	mock := &LoanApprovalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoanApprovalRepository is an autogenerated mock type for the LoanApprovalRepository type
type LoanApprovalRepository struct {
	mock.Mock
}

type LoanApprovalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LoanApprovalRepository) EXPECT() *LoanApprovalRepository_Expecter {
	return &LoanApprovalRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type LoanApprovalRepository
func (_mock *LoanApprovalRepository) Create(ctx context.Context, approval *models.LoanApproval) error {
	ret := _mock.Called(ctx, approval)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LoanApproval) error); ok {
		r0 = returnFunc(ctx, approval)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanApprovalRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LoanApprovalRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - approval *models.LoanApproval
func (_e *LoanApprovalRepository_Expecter) Create(ctx interface{}, approval interface{}) *LoanApprovalRepository_Create_Call {
	return &LoanApprovalRepository_Create_Call{Call: _e.mock.On("Create", ctx, approval)}
}

func (_c *LoanApprovalRepository_Create_Call) Run(run func(ctx context.Context, approval *models.LoanApproval)) *LoanApprovalRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LoanApproval
		if args[1] != nil {
			arg1 = args[1].(*models.LoanApproval)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanApprovalRepository_Create_Call) Return(err error) *LoanApprovalRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanApprovalRepository_Create_Call) RunAndReturn(run func(ctx context.Context, approval *models.LoanApproval) error) *LoanApprovalRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type LoanApprovalRepository
func (_mock *LoanApprovalRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanApprovalRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LoanApprovalRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanApprovalRepository_Expecter) Delete(ctx interface{}, id interface{}) *LoanApprovalRepository_Delete_Call {
	return &LoanApprovalRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *LoanApprovalRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *LoanApprovalRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanApprovalRepository_Delete_Call) Return(err error) *LoanApprovalRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanApprovalRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *LoanApprovalRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type LoanApprovalRepository
func (_mock *LoanApprovalRepository) GetByID(ctx context.Context, id int) (*models.LoanApproval, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.LoanApproval
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.LoanApproval, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.LoanApproval); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanApproval)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanApprovalRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LoanApprovalRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanApprovalRepository_Expecter) GetByID(ctx interface{}, id interface{}) *LoanApprovalRepository_GetByID_Call {
	return &LoanApprovalRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *LoanApprovalRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *LoanApprovalRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanApprovalRepository_GetByID_Call) Return(loanApproval *models.LoanApproval, err error) *LoanApprovalRepository_GetByID_Call {
	_c.Call.Return(loanApproval, err)
	return _c
}

func (_c *LoanApprovalRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.LoanApproval, error)) *LoanApprovalRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLoanID provides a mock function for the type LoanApprovalRepository
func (_mock *LoanApprovalRepository) GetByLoanID(ctx context.Context, loanID int) (*models.LoanApproval, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLoanID")
	}

	var r0 *models.LoanApproval
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.LoanApproval, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.LoanApproval); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanApproval)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanApprovalRepository_GetByLoanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLoanID'
type LoanApprovalRepository_GetByLoanID_Call struct {
	*mock.Call
}

// GetByLoanID is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
func (_e *LoanApprovalRepository_Expecter) GetByLoanID(ctx interface{}, loanID interface{}) *LoanApprovalRepository_GetByLoanID_Call {
	return &LoanApprovalRepository_GetByLoanID_Call{Call: _e.mock.On("GetByLoanID", ctx, loanID)}
}

func (_c *LoanApprovalRepository_GetByLoanID_Call) Run(run func(ctx context.Context, loanID int)) *LoanApprovalRepository_GetByLoanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanApprovalRepository_GetByLoanID_Call) Return(loanApproval *models.LoanApproval, err error) *LoanApprovalRepository_GetByLoanID_Call {
	_c.Call.Return(loanApproval, err)
	return _c
}

func (_c *LoanApprovalRepository_GetByLoanID_Call) RunAndReturn(run func(ctx context.Context, loanID int) (*models.LoanApproval, error)) *LoanApprovalRepository_GetByLoanID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type LoanApprovalRepository
func (_mock *LoanApprovalRepository) Update(ctx context.Context, approval *models.LoanApproval) error {
	ret := _mock.Called(ctx, approval)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LoanApproval) error); ok {
		r0 = returnFunc(ctx, approval)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanApprovalRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LoanApprovalRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - approval *models.LoanApproval
func (_e *LoanApprovalRepository_Expecter) Update(ctx interface{}, approval interface{}) *LoanApprovalRepository_Update_Call {
	return &LoanApprovalRepository_Update_Call{Call: _e.mock.On("Update", ctx, approval)}
}

func (_c *LoanApprovalRepository_Update_Call) Run(run func(ctx context.Context, approval *models.LoanApproval)) *LoanApprovalRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LoanApproval
		if args[1] != nil {
			arg1 = args[1].(*models.LoanApproval)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanApprovalRepository_Update_Call) Return(err error) *LoanApprovalRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanApprovalRepository_Update_Call) RunAndReturn(run func(ctx context.Context, approval *models.LoanApproval) error) *LoanApprovalRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
