// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewLoanDisbursementRepository creates a new instance of LoanDisbursementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanDisbursementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanDisbursementRepository {
	mock := &LoanDisbursementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoanDisbursementRepository is an autogenerated mock type for the LoanDisbursementRepository type
type LoanDisbursementRepository struct {
	mock.Mock
}

type LoanDisbursementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LoanDisbursementRepository) EXPECT() *LoanDisbursementRepository_Expecter {
	return &LoanDisbursementRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type LoanDisbursementRepository
func (_mock *LoanDisbursementRepository) Create(ctx context.Context, disbursement *models.LoanDisbursement) error {
	ret := _mock.Called(ctx, disbursement)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LoanDisbursement) error); ok {
		r0 = returnFunc(ctx, disbursement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanDisbursementRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LoanDisbursementRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - disbursement *models.LoanDisbursement
func (_e *LoanDisbursementRepository_Expecter) Create(ctx interface{}, disbursement interface{}) *LoanDisbursementRepository_Create_Call {
	return &LoanDisbursementRepository_Create_Call{Call: _e.mock.On("Create", ctx, disbursement)}
}

func (_c *LoanDisbursementRepository_Create_Call) Run(run func(ctx context.Context, disbursement *models.LoanDisbursement)) *LoanDisbursementRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LoanDisbursement
		if args[1] != nil {
			arg1 = args[1].(*models.LoanDisbursement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanDisbursementRepository_Create_Call) Return(err error) *LoanDisbursementRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanDisbursementRepository_Create_Call) RunAndReturn(run func(ctx context.Context, disbursement *models.LoanDisbursement) error) *LoanDisbursementRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type LoanDisbursementRepository
func (_mock *LoanDisbursementRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanDisbursementRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LoanDisbursementRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanDisbursementRepository_Expecter) Delete(ctx interface{}, id interface{}) *LoanDisbursementRepository_Delete_Call {
	return &LoanDisbursementRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *LoanDisbursementRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *LoanDisbursementRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanDisbursementRepository_Delete_Call) Return(err error) *LoanDisbursementRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanDisbursementRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *LoanDisbursementRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type LoanDisbursementRepository
func (_mock *LoanDisbursementRepository) GetByID(ctx context.Context, id int) (*models.LoanDisbursement, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.LoanDisbursement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.LoanDisbursement, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.LoanDisbursement); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanDisbursement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanDisbursementRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LoanDisbursementRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanDisbursementRepository_Expecter) GetByID(ctx interface{}, id interface{}) *LoanDisbursementRepository_GetByID_Call {
	return &LoanDisbursementRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *LoanDisbursementRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *LoanDisbursementRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanDisbursementRepository_GetByID_Call) Return(loanDisbursement *models.LoanDisbursement, err error) *LoanDisbursementRepository_GetByID_Call {
	_c.Call.Return(loanDisbursement, err)
	return _c
}

func (_c *LoanDisbursementRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.LoanDisbursement, error)) *LoanDisbursementRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLoanID provides a mock function for the type LoanDisbursementRepository
func (_mock *LoanDisbursementRepository) GetByLoanID(ctx context.Context, loanID int) (*models.LoanDisbursement, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLoanID")
	}

	var r0 *models.LoanDisbursement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.LoanDisbursement, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.LoanDisbursement); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanDisbursement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanDisbursementRepository_GetByLoanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLoanID'
type LoanDisbursementRepository_GetByLoanID_Call struct {
	*mock.Call
}

// GetByLoanID is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
func (_e *LoanDisbursementRepository_Expecter) GetByLoanID(ctx interface{}, loanID interface{}) *LoanDisbursementRepository_GetByLoanID_Call {
	return &LoanDisbursementRepository_GetByLoanID_Call{Call: _e.mock.On("GetByLoanID", ctx, loanID)}
}

func (_c *LoanDisbursementRepository_GetByLoanID_Call) Run(run func(ctx context.Context, loanID int)) *LoanDisbursementRepository_GetByLoanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanDisbursementRepository_GetByLoanID_Call) Return(loanDisbursement *models.LoanDisbursement, err error) *LoanDisbursementRepository_GetByLoanID_Call {
	_c.Call.Return(loanDisbursement, err)
	return _c
}

func (_c *LoanDisbursementRepository_GetByLoanID_Call) RunAndReturn(run func(ctx context.Context, loanID int) (*models.LoanDisbursement, error)) *LoanDisbursementRepository_GetByLoanID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type LoanDisbursementRepository
func (_mock *LoanDisbursementRepository) Update(ctx context.Context, disbursement *models.LoanDisbursement) error {
	ret := _mock.Called(ctx, disbursement)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LoanDisbursement) error); ok {
		r0 = returnFunc(ctx, disbursement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanDisbursementRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LoanDisbursementRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - disbursement *models.LoanDisbursement
func (_e *LoanDisbursementRepository_Expecter) Update(ctx interface{}, disbursement interface{}) *LoanDisbursementRepository_Update_Call {
	return &LoanDisbursementRepository_Update_Call{Call: _e.mock.On("Update", ctx, disbursement)}
}

func (_c *LoanDisbursementRepository_Update_Call) Run(run func(ctx context.Context, disbursement *models.LoanDisbursement)) *LoanDisbursementRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LoanDisbursement
		if args[1] != nil {
			arg1 = args[1].(*models.LoanDisbursement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanDisbursementRepository_Update_Call) Return(err error) *LoanDisbursementRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanDisbursementRepository_Update_Call) RunAndReturn(run func(ctx context.Context, disbursement *models.LoanDisbursement) error) *LoanDisbursementRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
