// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewLoanInvestmentRepository creates a new instance of LoanInvestmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanInvestmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanInvestmentRepository {
	mock := &LoanInvestmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoanInvestmentRepository is an autogenerated mock type for the LoanInvestmentRepository type
type LoanInvestmentRepository struct {
	mock.Mock
}

type LoanInvestmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LoanInvestmentRepository) EXPECT() *LoanInvestmentRepository_Expecter {
	return &LoanInvestmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type LoanInvestmentRepository
func (_mock *LoanInvestmentRepository) Create(ctx context.Context, investment *models.LoanInvestment) error {
	ret := _mock.Called(ctx, investment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LoanInvestment) error); ok {
		r0 = returnFunc(ctx, investment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanInvestmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LoanInvestmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - investment *models.LoanInvestment
func (_e *LoanInvestmentRepository_Expecter) Create(ctx interface{}, investment interface{}) *LoanInvestmentRepository_Create_Call {
	return &LoanInvestmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, investment)}
}

func (_c *LoanInvestmentRepository_Create_Call) Run(run func(ctx context.Context, investment *models.LoanInvestment)) *LoanInvestmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LoanInvestment
		if args[1] != nil {
			arg1 = args[1].(*models.LoanInvestment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanInvestmentRepository_Create_Call) Return(err error) *LoanInvestmentRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanInvestmentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, investment *models.LoanInvestment) error) *LoanInvestmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type LoanInvestmentRepository
func (_mock *LoanInvestmentRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanInvestmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LoanInvestmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanInvestmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *LoanInvestmentRepository_Delete_Call {
	return &LoanInvestmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *LoanInvestmentRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *LoanInvestmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanInvestmentRepository_Delete_Call) Return(err error) *LoanInvestmentRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanInvestmentRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *LoanInvestmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type LoanInvestmentRepository
func (_mock *LoanInvestmentRepository) GetByID(ctx context.Context, id int) (*models.LoanInvestment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.LoanInvestment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.LoanInvestment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.LoanInvestment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanInvestment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanInvestmentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LoanInvestmentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanInvestmentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *LoanInvestmentRepository_GetByID_Call {
	return &LoanInvestmentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *LoanInvestmentRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *LoanInvestmentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanInvestmentRepository_GetByID_Call) Return(loanInvestment *models.LoanInvestment, err error) *LoanInvestmentRepository_GetByID_Call {
	_c.Call.Return(loanInvestment, err)
	return _c
}

func (_c *LoanInvestmentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.LoanInvestment, error)) *LoanInvestmentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByInvestorID provides a mock function for the type LoanInvestmentRepository
func (_mock *LoanInvestmentRepository) GetByInvestorID(ctx context.Context, investorID int) ([]*models.LoanInvestment, error) {
	ret := _mock.Called(ctx, investorID)

	if len(ret) == 0 {
		panic("no return value specified for GetByInvestorID")
	}

	var r0 []*models.LoanInvestment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.LoanInvestment, error)); ok {
		return returnFunc(ctx, investorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.LoanInvestment); ok {
		r0 = returnFunc(ctx, investorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LoanInvestment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, investorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanInvestmentRepository_GetByInvestorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByInvestorID'
type LoanInvestmentRepository_GetByInvestorID_Call struct {
	*mock.Call
}

// GetByInvestorID is a helper method to define mock.On call
//   - ctx context.Context
//   - investorID int
func (_e *LoanInvestmentRepository_Expecter) GetByInvestorID(ctx interface{}, investorID interface{}) *LoanInvestmentRepository_GetByInvestorID_Call {
	return &LoanInvestmentRepository_GetByInvestorID_Call{Call: _e.mock.On("GetByInvestorID", ctx, investorID)}
}

func (_c *LoanInvestmentRepository_GetByInvestorID_Call) Run(run func(ctx context.Context, investorID int)) *LoanInvestmentRepository_GetByInvestorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanInvestmentRepository_GetByInvestorID_Call) Return(loanInvestments []*models.LoanInvestment, err error) *LoanInvestmentRepository_GetByInvestorID_Call {
	_c.Call.Return(loanInvestments, err)
	return _c
}

func (_c *LoanInvestmentRepository_GetByInvestorID_Call) RunAndReturn(run func(ctx context.Context, investorID int) ([]*models.LoanInvestment, error)) *LoanInvestmentRepository_GetByInvestorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLoanAndInvestor provides a mock function for the type LoanInvestmentRepository
func (_mock *LoanInvestmentRepository) GetByLoanAndInvestor(ctx context.Context, loanID int, investorID int) (*models.LoanInvestment, error) {
	ret := _mock.Called(ctx, loanID, investorID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLoanAndInvestor")
	}

	var r0 *models.LoanInvestment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*models.LoanInvestment, error)); ok {
		return returnFunc(ctx, loanID, investorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *models.LoanInvestment); ok {
		r0 = returnFunc(ctx, loanID, investorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanInvestment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, loanID, investorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanInvestmentRepository_GetByLoanAndInvestor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLoanAndInvestor'
type LoanInvestmentRepository_GetByLoanAndInvestor_Call struct {
	*mock.Call
}

// GetByLoanAndInvestor is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
//   - investorID int
func (_e *LoanInvestmentRepository_Expecter) GetByLoanAndInvestor(ctx interface{}, loanID interface{}, investorID interface{}) *LoanInvestmentRepository_GetByLoanAndInvestor_Call {
	return &LoanInvestmentRepository_GetByLoanAndInvestor_Call{Call: _e.mock.On("GetByLoanAndInvestor", ctx, loanID, investorID)}
}

func (_c *LoanInvestmentRepository_GetByLoanAndInvestor_Call) Run(run func(ctx context.Context, loanID int, investorID int)) *LoanInvestmentRepository_GetByLoanAndInvestor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoanInvestmentRepository_GetByLoanAndInvestor_Call) Return(loanInvestment *models.LoanInvestment, err error) *LoanInvestmentRepository_GetByLoanAndInvestor_Call {
	_c.Call.Return(loanInvestment, err)
	return _c
}

func (_c *LoanInvestmentRepository_GetByLoanAndInvestor_Call) RunAndReturn(run func(ctx context.Context, loanID int, investorID int) (*models.LoanInvestment, error)) *LoanInvestmentRepository_GetByLoanAndInvestor_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLoanID provides a mock function for the type LoanInvestmentRepository
func (_mock *LoanInvestmentRepository) GetByLoanID(ctx context.Context, loanID int) ([]*models.LoanInvestment, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLoanID")
	}

	var r0 []*models.LoanInvestment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.LoanInvestment, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.LoanInvestment); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LoanInvestment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanInvestmentRepository_GetByLoanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLoanID'
type LoanInvestmentRepository_GetByLoanID_Call struct {
	*mock.Call
}

// GetByLoanID is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
func (_e *LoanInvestmentRepository_Expecter) GetByLoanID(ctx interface{}, loanID interface{}) *LoanInvestmentRepository_GetByLoanID_Call {
	return &LoanInvestmentRepository_GetByLoanID_Call{Call: _e.mock.On("GetByLoanID", ctx, loanID)}
}

func (_c *LoanInvestmentRepository_GetByLoanID_Call) Run(run func(ctx context.Context, loanID int)) *LoanInvestmentRepository_GetByLoanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanInvestmentRepository_GetByLoanID_Call) Return(loanInvestments []*models.LoanInvestment, err error) *LoanInvestmentRepository_GetByLoanID_Call {
	_c.Call.Return(loanInvestments, err)
	return _c
}

func (_c *LoanInvestmentRepository_GetByLoanID_Call) RunAndReturn(run func(ctx context.Context, loanID int) ([]*models.LoanInvestment, error)) *LoanInvestmentRepository_GetByLoanID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalInvestedAmountByLoan provides a mock function for the type LoanInvestmentRepository
func (_mock *LoanInvestmentRepository) GetTotalInvestedAmountByLoan(ctx context.Context, loanID int) (float64, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalInvestedAmountByLoan")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (float64, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) float64); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalInvestedAmountByLoan'
type LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call struct {
	*mock.Call
}

// GetTotalInvestedAmountByLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
func (_e *LoanInvestmentRepository_Expecter) GetTotalInvestedAmountByLoan(ctx interface{}, loanID interface{}) *LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call {
	return &LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call{Call: _e.mock.On("GetTotalInvestedAmountByLoan", ctx, loanID)}
}

func (_c *LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call) Run(run func(ctx context.Context, loanID int)) *LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call) Return(f float64, err error) *LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call) RunAndReturn(run func(ctx context.Context, loanID int) (float64, error)) *LoanInvestmentRepository_GetTotalInvestedAmountByLoan_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type LoanInvestmentRepository
func (_mock *LoanInvestmentRepository) Update(ctx context.Context, investment *models.LoanInvestment) error {
	ret := _mock.Called(ctx, investment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LoanInvestment) error); ok {
		r0 = returnFunc(ctx, investment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanInvestmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LoanInvestmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - investment *models.LoanInvestment
func (_e *LoanInvestmentRepository_Expecter) Update(ctx interface{}, investment interface{}) *LoanInvestmentRepository_Update_Call {
	return &LoanInvestmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, investment)}
}

func (_c *LoanInvestmentRepository_Update_Call) Run(run func(ctx context.Context, investment *models.LoanInvestment)) *LoanInvestmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LoanInvestment
		if args[1] != nil {
			arg1 = args[1].(*models.LoanInvestment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanInvestmentRepository_Update_Call) Return(err error) *LoanInvestmentRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanInvestmentRepository_Update_Call) RunAndReturn(run func(ctx context.Context, investment *models.LoanInvestment) error) *LoanInvestmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
