// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewLoanStateHistoryRepository creates a new instance of LoanStateHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanStateHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanStateHistoryRepository {
	mock := &LoanStateHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoanStateHistoryRepository is an autogenerated mock type for the LoanStateHistoryRepository type
type LoanStateHistoryRepository struct {
	mock.Mock
}

type LoanStateHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LoanStateHistoryRepository) EXPECT() *LoanStateHistoryRepository_Expecter {
	return &LoanStateHistoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type LoanStateHistoryRepository
func (_mock *LoanStateHistoryRepository) Create(ctx context.Context, history *models.LoanStateHistory) error {
	ret := _mock.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LoanStateHistory) error); ok {
		r0 = returnFunc(ctx, history)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanStateHistoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LoanStateHistoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - history *models.LoanStateHistory
func (_e *LoanStateHistoryRepository_Expecter) Create(ctx interface{}, history interface{}) *LoanStateHistoryRepository_Create_Call {
	return &LoanStateHistoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, history)}
}

func (_c *LoanStateHistoryRepository_Create_Call) Run(run func(ctx context.Context, history *models.LoanStateHistory)) *LoanStateHistoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LoanStateHistory
		if args[1] != nil {
			arg1 = args[1].(*models.LoanStateHistory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanStateHistoryRepository_Create_Call) Return(err error) *LoanStateHistoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanStateHistoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, history *models.LoanStateHistory) error) *LoanStateHistoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLoanID provides a mock function for the type LoanStateHistoryRepository
func (_mock *LoanStateHistoryRepository) GetByLoanID(ctx context.Context, loanID int) ([]*models.LoanStateHistory, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLoanID")
	}

	var r0 []*models.LoanStateHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.LoanStateHistory, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.LoanStateHistory); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LoanStateHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanStateHistoryRepository_GetByLoanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLoanID'
type LoanStateHistoryRepository_GetByLoanID_Call struct {
	*mock.Call
}

// GetByLoanID is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
func (_e *LoanStateHistoryRepository_Expecter) GetByLoanID(ctx interface{}, loanID interface{}) *LoanStateHistoryRepository_GetByLoanID_Call {
	return &LoanStateHistoryRepository_GetByLoanID_Call{Call: _e.mock.On("GetByLoanID", ctx, loanID)}
}

func (_c *LoanStateHistoryRepository_GetByLoanID_Call) Run(run func(ctx context.Context, loanID int)) *LoanStateHistoryRepository_GetByLoanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanStateHistoryRepository_GetByLoanID_Call) Return(loanStateHistorys []*models.LoanStateHistory, err error) *LoanStateHistoryRepository_GetByLoanID_Call {
	_c.Call.Return(loanStateHistorys, err)
	return _c
}

func (_c *LoanStateHistoryRepository_GetByLoanID_Call) RunAndReturn(run func(ctx context.Context, loanID int) ([]*models.LoanStateHistory, error)) *LoanStateHistoryRepository_GetByLoanID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestByLoanID provides a mock function for the type LoanStateHistoryRepository
func (_mock *LoanStateHistoryRepository) GetLatestByLoanID(ctx context.Context, loanID int) (*models.LoanStateHistory, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByLoanID")
	}

	var r0 *models.LoanStateHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.LoanStateHistory, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.LoanStateHistory); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanStateHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanStateHistoryRepository_GetLatestByLoanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestByLoanID'
type LoanStateHistoryRepository_GetLatestByLoanID_Call struct {
	*mock.Call
}

// GetLatestByLoanID is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
func (_e *LoanStateHistoryRepository_Expecter) GetLatestByLoanID(ctx interface{}, loanID interface{}) *LoanStateHistoryRepository_GetLatestByLoanID_Call {
	return &LoanStateHistoryRepository_GetLatestByLoanID_Call{Call: _e.mock.On("GetLatestByLoanID", ctx, loanID)}
}

func (_c *LoanStateHistoryRepository_GetLatestByLoanID_Call) Run(run func(ctx context.Context, loanID int)) *LoanStateHistoryRepository_GetLatestByLoanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanStateHistoryRepository_GetLatestByLoanID_Call) Return(loanStateHistory *models.LoanStateHistory, err error) *LoanStateHistoryRepository_GetLatestByLoanID_Call {
	_c.Call.Return(loanStateHistory, err)
	return _c
}

func (_c *LoanStateHistoryRepository_GetLatestByLoanID_Call) RunAndReturn(run func(ctx context.Context, loanID int) (*models.LoanStateHistory, error)) *LoanStateHistoryRepository_GetLatestByLoanID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type LoanStateHistoryRepository
func (_mock *LoanStateHistoryRepository) List(ctx context.Context, loanID int, offset int, limit int) ([]*models.LoanStateHistory, error) {
	ret := _mock.Called(ctx, loanID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.LoanStateHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*models.LoanStateHistory, error)); ok {
		return returnFunc(ctx, loanID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) []*models.LoanStateHistory); ok {
		r0 = returnFunc(ctx, loanID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LoanStateHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = returnFunc(ctx, loanID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanStateHistoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type LoanStateHistoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
//   - offset int
//   - limit int
func (_e *LoanStateHistoryRepository_Expecter) List(ctx interface{}, loanID interface{}, offset interface{}, limit interface{}) *LoanStateHistoryRepository_List_Call {
	return &LoanStateHistoryRepository_List_Call{Call: _e.mock.On("List", ctx, loanID, offset, limit)}
}

func (_c *LoanStateHistoryRepository_List_Call) Run(run func(ctx context.Context, loanID int, offset int, limit int)) *LoanStateHistoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *LoanStateHistoryRepository_List_Call) Return(loanStateHistorys []*models.LoanStateHistory, err error) *LoanStateHistoryRepository_List_Call {
	_c.Call.Return(loanStateHistorys, err)
	return _c
}

func (_c *LoanStateHistoryRepository_List_Call) RunAndReturn(run func(ctx context.Context, loanID int, offset int, limit int) ([]*models.LoanStateHistory, error)) *LoanStateHistoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
