// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewLoanRepository creates a new instance of LoanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanRepository {
	mock := &LoanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoanRepository is an autogenerated mock type for the LoanRepository type
type LoanRepository struct {
	mock.Mock
}

type LoanRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LoanRepository) EXPECT() *LoanRepository_Expecter {
	return &LoanRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type LoanRepository
func (_mock *LoanRepository) Create(ctx context.Context, loan *models.Loan) error {
	ret := _mock.Called(ctx, loan)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Loan) error); ok {
		r0 = returnFunc(ctx, loan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LoanRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - loan *models.Loan
func (_e *LoanRepository_Expecter) Create(ctx interface{}, loan interface{}) *LoanRepository_Create_Call {
	return &LoanRepository_Create_Call{Call: _e.mock.On("Create", ctx, loan)}
}

func (_c *LoanRepository_Create_Call) Run(run func(ctx context.Context, loan *models.Loan)) *LoanRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Loan
		if args[1] != nil {
			arg1 = args[1].(*models.Loan)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanRepository_Create_Call) Return(err error) *LoanRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanRepository_Create_Call) RunAndReturn(run func(ctx context.Context, loan *models.Loan) error) *LoanRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type LoanRepository
func (_mock *LoanRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LoanRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanRepository_Expecter) Delete(ctx interface{}, id interface{}) *LoanRepository_Delete_Call {
	return &LoanRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *LoanRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *LoanRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanRepository_Delete_Call) Return(err error) *LoanRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *LoanRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type LoanRepository
func (_mock *LoanRepository) GetByID(ctx context.Context, id int) (*models.Loan, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Loan, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Loan); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LoanRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanRepository_Expecter) GetByID(ctx interface{}, id interface{}) *LoanRepository_GetByID_Call {
	return &LoanRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *LoanRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *LoanRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanRepository_GetByID_Call) Return(loan *models.Loan, err error) *LoanRepository_GetByID_Call {
	_c.Call.Return(loan, err)
	return _c
}

func (_c *LoanRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Loan, error)) *LoanRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLoanID provides a mock function for the type LoanRepository
func (_mock *LoanRepository) GetByLoanID(ctx context.Context, loanID string) (*models.Loan, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLoanID")
	}

	var r0 *models.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Loan, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Loan); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanRepository_GetByLoanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLoanID'
type LoanRepository_GetByLoanID_Call struct {
	*mock.Call
}

// GetByLoanID is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID string
func (_e *LoanRepository_Expecter) GetByLoanID(ctx interface{}, loanID interface{}) *LoanRepository_GetByLoanID_Call {
	return &LoanRepository_GetByLoanID_Call{Call: _e.mock.On("GetByLoanID", ctx, loanID)}
}

func (_c *LoanRepository_GetByLoanID_Call) Run(run func(ctx context.Context, loanID string)) *LoanRepository_GetByLoanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanRepository_GetByLoanID_Call) Return(loan *models.Loan, err error) *LoanRepository_GetByLoanID_Call {
	_c.Call.Return(loan, err)
	return _c
}

func (_c *LoanRepository_GetByLoanID_Call) RunAndReturn(run func(ctx context.Context, loanID string) (*models.Loan, error)) *LoanRepository_GetByLoanID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByState provides a mock function for the type LoanRepository
func (_mock *LoanRepository) GetByState(ctx context.Context, state string) ([]*models.Loan, error) {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for GetByState")
	}

	var r0 []*models.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.Loan, error)); ok {
		return returnFunc(ctx, state)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.Loan); ok {
		r0 = returnFunc(ctx, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanRepository_GetByState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByState'
type LoanRepository_GetByState_Call struct {
	*mock.Call
}

// GetByState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *LoanRepository_Expecter) GetByState(ctx interface{}, state interface{}) *LoanRepository_GetByState_Call {
	return &LoanRepository_GetByState_Call{Call: _e.mock.On("GetByState", ctx, state)}
}

func (_c *LoanRepository_GetByState_Call) Run(run func(ctx context.Context, state string)) *LoanRepository_GetByState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanRepository_GetByState_Call) Return(loans []*models.Loan, err error) *LoanRepository_GetByState_Call {
	_c.Call.Return(loans, err)
	return _c
}

func (_c *LoanRepository_GetByState_Call) RunAndReturn(run func(ctx context.Context, state string) ([]*models.Loan, error)) *LoanRepository_GetByState_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalInvestedAmount provides a mock function for the type LoanRepository
func (_mock *LoanRepository) GetTotalInvestedAmount(ctx context.Context, loanID int) (float64, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalInvestedAmount")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (float64, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) float64); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanRepository_GetTotalInvestedAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalInvestedAmount'
type LoanRepository_GetTotalInvestedAmount_Call struct {
	*mock.Call
}

// GetTotalInvestedAmount is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
func (_e *LoanRepository_Expecter) GetTotalInvestedAmount(ctx interface{}, loanID interface{}) *LoanRepository_GetTotalInvestedAmount_Call {
	return &LoanRepository_GetTotalInvestedAmount_Call{Call: _e.mock.On("GetTotalInvestedAmount", ctx, loanID)}
}

func (_c *LoanRepository_GetTotalInvestedAmount_Call) Run(run func(ctx context.Context, loanID int)) *LoanRepository_GetTotalInvestedAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanRepository_GetTotalInvestedAmount_Call) Return(f float64, err error) *LoanRepository_GetTotalInvestedAmount_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *LoanRepository_GetTotalInvestedAmount_Call) RunAndReturn(run func(ctx context.Context, loanID int) (float64, error)) *LoanRepository_GetTotalInvestedAmount_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type LoanRepository
func (_mock *LoanRepository) List(ctx context.Context, state *string, offset int, limit int) ([]*models.Loan, error) {
	ret := _mock.Called(ctx, state, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int, int) ([]*models.Loan, error)); ok {
		return returnFunc(ctx, state, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int, int) []*models.Loan); ok {
		r0 = returnFunc(ctx, state, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, int, int) error); ok {
		r1 = returnFunc(ctx, state, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type LoanRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - state *string
//   - offset int
//   - limit int
func (_e *LoanRepository_Expecter) List(ctx interface{}, state interface{}, offset interface{}, limit interface{}) *LoanRepository_List_Call {
	return &LoanRepository_List_Call{Call: _e.mock.On("List", ctx, state, offset, limit)}
}

func (_c *LoanRepository_List_Call) Run(run func(ctx context.Context, state *string, offset int, limit int)) *LoanRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *LoanRepository_List_Call) Return(loans []*models.Loan, err error) *LoanRepository_List_Call {
	_c.Call.Return(loans, err)
	return _c
}

func (_c *LoanRepository_List_Call) RunAndReturn(run func(ctx context.Context, state *string, offset int, limit int) ([]*models.Loan, error)) *LoanRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type LoanRepository
func (_mock *LoanRepository) Update(ctx context.Context, loan *models.Loan) error {
	ret := _mock.Called(ctx, loan)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Loan) error); ok {
		r0 = returnFunc(ctx, loan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LoanRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - loan *models.Loan
func (_e *LoanRepository_Expecter) Update(ctx interface{}, loan interface{}) *LoanRepository_Update_Call {
	return &LoanRepository_Update_Call{Call: _e.mock.On("Update", ctx, loan)}
}

func (_c *LoanRepository_Update_Call) Run(run func(ctx context.Context, loan *models.Loan)) *LoanRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Loan
		if args[1] != nil {
			arg1 = args[1].(*models.Loan)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanRepository_Update_Call) Return(err error) *LoanRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanRepository_Update_Call) RunAndReturn(run func(ctx context.Context, loan *models.Loan) error) *LoanRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function for the type LoanRepository
func (_mock *LoanRepository) UpdateState(ctx context.Context, id int, newState string) error {
	ret := _mock.Called(ctx, id, newState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, id, newState)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanRepository_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type LoanRepository_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - newState string
func (_e *LoanRepository_Expecter) UpdateState(ctx interface{}, id interface{}, newState interface{}) *LoanRepository_UpdateState_Call {
	return &LoanRepository_UpdateState_Call{Call: _e.mock.On("UpdateState", ctx, id, newState)}
}

func (_c *LoanRepository_UpdateState_Call) Run(run func(ctx context.Context, id int, newState string)) *LoanRepository_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoanRepository_UpdateState_Call) Return(err error) *LoanRepository_UpdateState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanRepository_UpdateState_Call) RunAndReturn(run func(ctx context.Context, id int, newState string) error) *LoanRepository_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTotalInvestedAmount provides a mock function for the type LoanRepository
func (_mock *LoanRepository) UpdateTotalInvestedAmount(ctx context.Context, loanID int, amount float64) error {
	ret := _mock.Called(ctx, loanID, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTotalInvestedAmount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, float64) error); ok {
		r0 = returnFunc(ctx, loanID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanRepository_UpdateTotalInvestedAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTotalInvestedAmount'
type LoanRepository_UpdateTotalInvestedAmount_Call struct {
	*mock.Call
}

// UpdateTotalInvestedAmount is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
//   - amount float64
func (_e *LoanRepository_Expecter) UpdateTotalInvestedAmount(ctx interface{}, loanID interface{}, amount interface{}) *LoanRepository_UpdateTotalInvestedAmount_Call {
	return &LoanRepository_UpdateTotalInvestedAmount_Call{Call: _e.mock.On("UpdateTotalInvestedAmount", ctx, loanID, amount)}
}

func (_c *LoanRepository_UpdateTotalInvestedAmount_Call) Run(run func(ctx context.Context, loanID int, amount float64)) *LoanRepository_UpdateTotalInvestedAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoanRepository_UpdateTotalInvestedAmount_Call) Return(err error) *LoanRepository_UpdateTotalInvestedAmount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanRepository_UpdateTotalInvestedAmount_Call) RunAndReturn(run func(ctx context.Context, loanID int, amount float64) error) *LoanRepository_UpdateTotalInvestedAmount_Call {
	_c.Call.Return(run)
	return _c
}
