// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// CheckPasswordHash provides a mock function for the type AuthService
func (_mock *AuthService) CheckPasswordHash(password string, hash string) bool {
	ret := _mock.Called(password, hash)

	if len(ret) == 0 {
		panic("no return value specified for CheckPasswordHash")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// AuthService_CheckPasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPasswordHash'
type AuthService_CheckPasswordHash_Call struct {
	*mock.Call
}

// CheckPasswordHash is a helper method to define mock.On call
//   - password string
//   - hash string
func (_e *AuthService_Expecter) CheckPasswordHash(password interface{}, hash interface{}) *AuthService_CheckPasswordHash_Call {
	return &AuthService_CheckPasswordHash_Call{Call: _e.mock.On("CheckPasswordHash", password, hash)}
}

func (_c *AuthService_CheckPasswordHash_Call) Run(run func(password string, hash string)) *AuthService_CheckPasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_CheckPasswordHash_Call) Return(b bool) *AuthService_CheckPasswordHash_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *AuthService_CheckPasswordHash_Call) RunAndReturn(run func(password string, hash string) bool) *AuthService_CheckPasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function for the type AuthService
func (_mock *AuthService) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type AuthService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *AuthService_Expecter) HashPassword(password interface{}) *AuthService_HashPassword_Call {
	return &AuthService_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *AuthService_HashPassword_Call) Run(run func(password string)) *AuthService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthService_HashPassword_Call) Return(s string, err error) *AuthService_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AuthService_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *AuthService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function for the type AuthService
func (_mock *AuthService) LoginUser(ctx context.Context, email string, password string) (string, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type AuthService_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *AuthService_Expecter) LoginUser(ctx interface{}, email interface{}, password interface{}) *AuthService_LoginUser_Call {
	return &AuthService_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, email, password)}
}

func (_c *AuthService_LoginUser_Call) Run(run func(ctx context.Context, email string, password string)) *AuthService_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_LoginUser_Call) Return(s string, err error) *AuthService_LoginUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AuthService_LoginUser_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (string, error)) *AuthService_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type AuthService
func (_mock *AuthService) RefreshToken(ctx context.Context, refreshToken string) (string, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type AuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthService_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *AuthService_RefreshToken_Call {
	return &AuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *AuthService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_RefreshToken_Call) Return(s string, err error) *AuthService_RefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AuthService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (string, error)) *AuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type AuthService
func (_mock *AuthService) RegisterUser(ctx context.Context, user *models.User, password string) error {
	ret := _mock.Called(ctx, user, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User, string) error); ok {
		r0 = returnFunc(ctx, user, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type AuthService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
//   - password string
func (_e *AuthService_Expecter) RegisterUser(ctx interface{}, user interface{}, password interface{}) *AuthService_RegisterUser_Call {
	return &AuthService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user, password)}
}

func (_c *AuthService_RegisterUser_Call) Run(run func(ctx context.Context, user *models.User, password string)) *AuthService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_RegisterUser_Call) Return(err error) *AuthService_RegisterUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, user *models.User, password string) error) *AuthService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type AuthService
func (_mock *AuthService) ValidateToken(ctx context.Context, token string) (*models.User, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type AuthService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthService_Expecter) ValidateToken(ctx interface{}, token interface{}) *AuthService_ValidateToken_Call {
	return &AuthService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *AuthService_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *AuthService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_ValidateToken_Call) Return(user *models.User, err error) *AuthService_ValidateToken_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthService_ValidateToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*models.User, error)) *AuthService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
