// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewBorrowerService creates a new instance of BorrowerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBorrowerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BorrowerService {
	mock := &BorrowerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BorrowerService is an autogenerated mock type for the BorrowerService type
type BorrowerService struct {
	mock.Mock
}

type BorrowerService_Expecter struct {
	mock *mock.Mock
}

func (_m *BorrowerService) EXPECT() *BorrowerService_Expecter {
	return &BorrowerService_Expecter{mock: &_m.Mock}
}

// CreateBorrower provides a mock function for the type BorrowerService
func (_mock *BorrowerService) CreateBorrower(ctx context.Context, borrower *models.Borrower) error {
	ret := _mock.Called(ctx, borrower)

	if len(ret) == 0 {
		panic("no return value specified for CreateBorrower")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Borrower) error); ok {
		r0 = returnFunc(ctx, borrower)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BorrowerService_CreateBorrower_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBorrower'
type BorrowerService_CreateBorrower_Call struct {
	*mock.Call
}

// CreateBorrower is a helper method to define mock.On call
//   - ctx context.Context
//   - borrower *models.Borrower
func (_e *BorrowerService_Expecter) CreateBorrower(ctx interface{}, borrower interface{}) *BorrowerService_CreateBorrower_Call {
	return &BorrowerService_CreateBorrower_Call{Call: _e.mock.On("CreateBorrower", ctx, borrower)}
}

func (_c *BorrowerService_CreateBorrower_Call) Run(run func(ctx context.Context, borrower *models.Borrower)) *BorrowerService_CreateBorrower_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Borrower
		if args[1] != nil {
			arg1 = args[1].(*models.Borrower)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerService_CreateBorrower_Call) Return(err error) *BorrowerService_CreateBorrower_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BorrowerService_CreateBorrower_Call) RunAndReturn(run func(ctx context.Context, borrower *models.Borrower) error) *BorrowerService_CreateBorrower_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBorrower provides a mock function for the type BorrowerService
func (_mock *BorrowerService) DeleteBorrower(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBorrower")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BorrowerService_DeleteBorrower_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBorrower'
type BorrowerService_DeleteBorrower_Call struct {
	*mock.Call
}

// DeleteBorrower is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *BorrowerService_Expecter) DeleteBorrower(ctx interface{}, id interface{}) *BorrowerService_DeleteBorrower_Call {
	return &BorrowerService_DeleteBorrower_Call{Call: _e.mock.On("DeleteBorrower", ctx, id)}
}

func (_c *BorrowerService_DeleteBorrower_Call) Run(run func(ctx context.Context, id int)) *BorrowerService_DeleteBorrower_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerService_DeleteBorrower_Call) Return(err error) *BorrowerService_DeleteBorrower_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BorrowerService_DeleteBorrower_Call) RunAndReturn(run func(ctx context.Context, id int) error) *BorrowerService_DeleteBorrower_Call {
	_c.Call.Return(run)
	return _c
}

// GetBorrowerByBorrowerIDNumber provides a mock function for the type BorrowerService
func (_mock *BorrowerService) GetBorrowerByBorrowerIDNumber(ctx context.Context, borrowerIDNumber string) (*models.Borrower, error) {
	ret := _mock.Called(ctx, borrowerIDNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBorrowerByBorrowerIDNumber")
	}

	var r0 *models.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Borrower, error)); ok {
		return returnFunc(ctx, borrowerIDNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Borrower); ok {
		r0 = returnFunc(ctx, borrowerIDNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, borrowerIDNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BorrowerService_GetBorrowerByBorrowerIDNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBorrowerByBorrowerIDNumber'
type BorrowerService_GetBorrowerByBorrowerIDNumber_Call struct {
	*mock.Call
}

// GetBorrowerByBorrowerIDNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - borrowerIDNumber string
func (_e *BorrowerService_Expecter) GetBorrowerByBorrowerIDNumber(ctx interface{}, borrowerIDNumber interface{}) *BorrowerService_GetBorrowerByBorrowerIDNumber_Call {
	return &BorrowerService_GetBorrowerByBorrowerIDNumber_Call{Call: _e.mock.On("GetBorrowerByBorrowerIDNumber", ctx, borrowerIDNumber)}
}

func (_c *BorrowerService_GetBorrowerByBorrowerIDNumber_Call) Run(run func(ctx context.Context, borrowerIDNumber string)) *BorrowerService_GetBorrowerByBorrowerIDNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerService_GetBorrowerByBorrowerIDNumber_Call) Return(borrower *models.Borrower, err error) *BorrowerService_GetBorrowerByBorrowerIDNumber_Call {
	_c.Call.Return(borrower, err)
	return _c
}

func (_c *BorrowerService_GetBorrowerByBorrowerIDNumber_Call) RunAndReturn(run func(ctx context.Context, borrowerIDNumber string) (*models.Borrower, error)) *BorrowerService_GetBorrowerByBorrowerIDNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetBorrowerByID provides a mock function for the type BorrowerService
func (_mock *BorrowerService) GetBorrowerByID(ctx context.Context, id int) (*models.Borrower, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBorrowerByID")
	}

	var r0 *models.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Borrower, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Borrower); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BorrowerService_GetBorrowerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBorrowerByID'
type BorrowerService_GetBorrowerByID_Call struct {
	*mock.Call
}

// GetBorrowerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *BorrowerService_Expecter) GetBorrowerByID(ctx interface{}, id interface{}) *BorrowerService_GetBorrowerByID_Call {
	return &BorrowerService_GetBorrowerByID_Call{Call: _e.mock.On("GetBorrowerByID", ctx, id)}
}

func (_c *BorrowerService_GetBorrowerByID_Call) Run(run func(ctx context.Context, id int)) *BorrowerService_GetBorrowerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BorrowerService_GetBorrowerByID_Call) Return(borrower *models.Borrower, err error) *BorrowerService_GetBorrowerByID_Call {
	_c.Call.Return(borrower, err)
	return _c
}

func (_c *BorrowerService_GetBorrowerByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Borrower, error)) *BorrowerService_GetBorrowerByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBorrowers provides a mock function for the type BorrowerService
func (_mock *BorrowerService) ListBorrowers(ctx context.Context, offset int, limit int) ([]*models.Borrower, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListBorrowers")
	}

	var r0 []*models.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Borrower, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*models.Borrower); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BorrowerService_ListBorrowers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBorrowers'
type BorrowerService_ListBorrowers_Call struct {
	*mock.Call
}

// ListBorrowers is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *BorrowerService_Expecter) ListBorrowers(ctx interface{}, offset interface{}, limit interface{}) *BorrowerService_ListBorrowers_Call {
	return &BorrowerService_ListBorrowers_Call{Call: _e.mock.On("ListBorrowers", ctx, offset, limit)}
}

func (_c *BorrowerService_ListBorrowers_Call) Run(run func(ctx context.Context, offset int, limit int)) *BorrowerService_ListBorrowers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BorrowerService_ListBorrowers_Call) Return(borrowers []*models.Borrower, err error) *BorrowerService_ListBorrowers_Call {
	_c.Call.Return(borrowers, err)
	return _c
}

func (_c *BorrowerService_ListBorrowers_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*models.Borrower, error)) *BorrowerService_ListBorrowers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBorrower provides a mock function for the type BorrowerService
func (_mock *BorrowerService) UpdateBorrower(ctx context.Context, id int, borrower *models.Borrower) error {
	ret := _mock.Called(ctx, id, borrower)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBorrower")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.Borrower) error); ok {
		r0 = returnFunc(ctx, id, borrower)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BorrowerService_UpdateBorrower_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBorrower'
type BorrowerService_UpdateBorrower_Call struct {
	*mock.Call
}

// UpdateBorrower is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - borrower *models.Borrower
func (_e *BorrowerService_Expecter) UpdateBorrower(ctx interface{}, id interface{}, borrower interface{}) *BorrowerService_UpdateBorrower_Call {
	return &BorrowerService_UpdateBorrower_Call{Call: _e.mock.On("UpdateBorrower", ctx, id, borrower)}
}

func (_c *BorrowerService_UpdateBorrower_Call) Run(run func(ctx context.Context, id int, borrower *models.Borrower)) *BorrowerService_UpdateBorrower_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.Borrower
		if args[2] != nil {
			arg2 = args[2].(*models.Borrower)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BorrowerService_UpdateBorrower_Call) Return(err error) *BorrowerService_UpdateBorrower_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BorrowerService_UpdateBorrower_Call) RunAndReturn(run func(ctx context.Context, id int, borrower *models.Borrower) error) *BorrowerService_UpdateBorrower_Call {
	_c.Call.Return(run)
	return _c
}
