// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewInvestorService creates a new instance of InvestorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvestorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvestorService {
	mock := &InvestorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InvestorService is an autogenerated mock type for the InvestorService type
type InvestorService struct {
	mock.Mock
}

type InvestorService_Expecter struct {
	mock *mock.Mock
}

func (_m *InvestorService) EXPECT() *InvestorService_Expecter {
	return &InvestorService_Expecter{mock: &_m.Mock}
}

// CreateInvestor provides a mock function for the type InvestorService
func (_mock *InvestorService) CreateInvestor(ctx context.Context, investor *models.Investor) error {
	ret := _mock.Called(ctx, investor)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvestor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Investor) error); ok {
		r0 = returnFunc(ctx, investor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvestorService_CreateInvestor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvestor'
type InvestorService_CreateInvestor_Call struct {
	*mock.Call
}

// CreateInvestor is a helper method to define mock.On call
//   - ctx context.Context
//   - investor *models.Investor
func (_e *InvestorService_Expecter) CreateInvestor(ctx interface{}, investor interface{}) *InvestorService_CreateInvestor_Call {
	return &InvestorService_CreateInvestor_Call{Call: _e.mock.On("CreateInvestor", ctx, investor)}
}

func (_c *InvestorService_CreateInvestor_Call) Run(run func(ctx context.Context, investor *models.Investor)) *InvestorService_CreateInvestor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Investor
		if args[1] != nil {
			arg1 = args[1].(*models.Investor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorService_CreateInvestor_Call) Return(err error) *InvestorService_CreateInvestor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvestorService_CreateInvestor_Call) RunAndReturn(run func(ctx context.Context, investor *models.Investor) error) *InvestorService_CreateInvestor_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInvestor provides a mock function for the type InvestorService
func (_mock *InvestorService) DeleteInvestor(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvestor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvestorService_DeleteInvestor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInvestor'
type InvestorService_DeleteInvestor_Call struct {
	*mock.Call
}

// DeleteInvestor is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *InvestorService_Expecter) DeleteInvestor(ctx interface{}, id interface{}) *InvestorService_DeleteInvestor_Call {
	return &InvestorService_DeleteInvestor_Call{Call: _e.mock.On("DeleteInvestor", ctx, id)}
}

func (_c *InvestorService_DeleteInvestor_Call) Run(run func(ctx context.Context, id int)) *InvestorService_DeleteInvestor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorService_DeleteInvestor_Call) Return(err error) *InvestorService_DeleteInvestor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvestorService_DeleteInvestor_Call) RunAndReturn(run func(ctx context.Context, id int) error) *InvestorService_DeleteInvestor_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvestorByEmail provides a mock function for the type InvestorService
func (_mock *InvestorService) GetInvestorByEmail(ctx context.Context, email string) (*models.Investor, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetInvestorByEmail")
	}

	var r0 *models.Investor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Investor, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Investor); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Investor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvestorService_GetInvestorByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvestorByEmail'
type InvestorService_GetInvestorByEmail_Call struct {
	*mock.Call
}

// GetInvestorByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *InvestorService_Expecter) GetInvestorByEmail(ctx interface{}, email interface{}) *InvestorService_GetInvestorByEmail_Call {
	return &InvestorService_GetInvestorByEmail_Call{Call: _e.mock.On("GetInvestorByEmail", ctx, email)}
}

func (_c *InvestorService_GetInvestorByEmail_Call) Run(run func(ctx context.Context, email string)) *InvestorService_GetInvestorByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorService_GetInvestorByEmail_Call) Return(investor *models.Investor, err error) *InvestorService_GetInvestorByEmail_Call {
	_c.Call.Return(investor, err)
	return _c
}

func (_c *InvestorService_GetInvestorByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.Investor, error)) *InvestorService_GetInvestorByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvestorByID provides a mock function for the type InvestorService
func (_mock *InvestorService) GetInvestorByID(ctx context.Context, id int) (*models.Investor, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInvestorByID")
	}

	var r0 *models.Investor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Investor, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Investor); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Investor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvestorService_GetInvestorByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvestorByID'
type InvestorService_GetInvestorByID_Call struct {
	*mock.Call
}

// GetInvestorByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *InvestorService_Expecter) GetInvestorByID(ctx interface{}, id interface{}) *InvestorService_GetInvestorByID_Call {
	return &InvestorService_GetInvestorByID_Call{Call: _e.mock.On("GetInvestorByID", ctx, id)}
}

func (_c *InvestorService_GetInvestorByID_Call) Run(run func(ctx context.Context, id int)) *InvestorService_GetInvestorByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorService_GetInvestorByID_Call) Return(investor *models.Investor, err error) *InvestorService_GetInvestorByID_Call {
	_c.Call.Return(investor, err)
	return _c
}

func (_c *InvestorService_GetInvestorByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Investor, error)) *InvestorService_GetInvestorByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvestorByInvestorID provides a mock function for the type InvestorService
func (_mock *InvestorService) GetInvestorByInvestorID(ctx context.Context, investorID string) (*models.Investor, error) {
	ret := _mock.Called(ctx, investorID)

	if len(ret) == 0 {
		panic("no return value specified for GetInvestorByInvestorID")
	}

	var r0 *models.Investor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Investor, error)); ok {
		return returnFunc(ctx, investorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Investor); ok {
		r0 = returnFunc(ctx, investorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Investor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, investorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvestorService_GetInvestorByInvestorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvestorByInvestorID'
type InvestorService_GetInvestorByInvestorID_Call struct {
	*mock.Call
}

// GetInvestorByInvestorID is a helper method to define mock.On call
//   - ctx context.Context
//   - investorID string
func (_e *InvestorService_Expecter) GetInvestorByInvestorID(ctx interface{}, investorID interface{}) *InvestorService_GetInvestorByInvestorID_Call {
	return &InvestorService_GetInvestorByInvestorID_Call{Call: _e.mock.On("GetInvestorByInvestorID", ctx, investorID)}
}

func (_c *InvestorService_GetInvestorByInvestorID_Call) Run(run func(ctx context.Context, investorID string)) *InvestorService_GetInvestorByInvestorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvestorService_GetInvestorByInvestorID_Call) Return(investor *models.Investor, err error) *InvestorService_GetInvestorByInvestorID_Call {
	_c.Call.Return(investor, err)
	return _c
}

func (_c *InvestorService_GetInvestorByInvestorID_Call) RunAndReturn(run func(ctx context.Context, investorID string) (*models.Investor, error)) *InvestorService_GetInvestorByInvestorID_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvestors provides a mock function for the type InvestorService
func (_mock *InvestorService) ListInvestors(ctx context.Context, offset int, limit int) ([]*models.Investor, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListInvestors")
	}

	var r0 []*models.Investor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Investor, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*models.Investor); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Investor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvestorService_ListInvestors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvestors'
type InvestorService_ListInvestors_Call struct {
	*mock.Call
}

// ListInvestors is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *InvestorService_Expecter) ListInvestors(ctx interface{}, offset interface{}, limit interface{}) *InvestorService_ListInvestors_Call {
	return &InvestorService_ListInvestors_Call{Call: _e.mock.On("ListInvestors", ctx, offset, limit)}
}

func (_c *InvestorService_ListInvestors_Call) Run(run func(ctx context.Context, offset int, limit int)) *InvestorService_ListInvestors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InvestorService_ListInvestors_Call) Return(investors []*models.Investor, err error) *InvestorService_ListInvestors_Call {
	_c.Call.Return(investors, err)
	return _c
}

func (_c *InvestorService_ListInvestors_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*models.Investor, error)) *InvestorService_ListInvestors_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInvestor provides a mock function for the type InvestorService
func (_mock *InvestorService) UpdateInvestor(ctx context.Context, id int, investor *models.Investor) error {
	ret := _mock.Called(ctx, id, investor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInvestor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.Investor) error); ok {
		r0 = returnFunc(ctx, id, investor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvestorService_UpdateInvestor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInvestor'
type InvestorService_UpdateInvestor_Call struct {
	*mock.Call
}

// UpdateInvestor is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - investor *models.Investor
func (_e *InvestorService_Expecter) UpdateInvestor(ctx interface{}, id interface{}, investor interface{}) *InvestorService_UpdateInvestor_Call {
	return &InvestorService_UpdateInvestor_Call{Call: _e.mock.On("UpdateInvestor", ctx, id, investor)}
}

func (_c *InvestorService_UpdateInvestor_Call) Run(run func(ctx context.Context, id int, investor *models.Investor)) *InvestorService_UpdateInvestor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.Investor
		if args[2] != nil {
			arg2 = args[2].(*models.Investor)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InvestorService_UpdateInvestor_Call) Return(err error) *InvestorService_UpdateInvestor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvestorService_UpdateInvestor_Call) RunAndReturn(run func(ctx context.Context, id int, investor *models.Investor) error) *InvestorService_UpdateInvestor_Call {
	_c.Call.Return(run)
	return _c
}
