// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sswastioyono18/loan-engine/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewLoanService creates a new instance of LoanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanService {
	mock := &LoanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoanService is an autogenerated mock type for the LoanService type
type LoanService struct {
	mock.Mock
}

type LoanService_Expecter struct {
	mock *mock.Mock
}

func (_m *LoanService) EXPECT() *LoanService_Expecter {
	return &LoanService_Expecter{mock: &_m.Mock}
}

// ApproveLoan provides a mock function for the type LoanService
func (_mock *LoanService) ApproveLoan(ctx context.Context, loanID int, approvalData *models.LoanApproval) error {
	ret := _mock.Called(ctx, loanID, approvalData)

	if len(ret) == 0 {
		panic("no return value specified for ApproveLoan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.LoanApproval) error); ok {
		r0 = returnFunc(ctx, loanID, approvalData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanService_ApproveLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveLoan'
type LoanService_ApproveLoan_Call struct {
	*mock.Call
}

// ApproveLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
//   - approvalData *models.LoanApproval
func (_e *LoanService_Expecter) ApproveLoan(ctx interface{}, loanID interface{}, approvalData interface{}) *LoanService_ApproveLoan_Call {
	return &LoanService_ApproveLoan_Call{Call: _e.mock.On("ApproveLoan", ctx, loanID, approvalData)}
}

func (_c *LoanService_ApproveLoan_Call) Run(run func(ctx context.Context, loanID int, approvalData *models.LoanApproval)) *LoanService_ApproveLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.LoanApproval
		if args[2] != nil {
			arg2 = args[2].(*models.LoanApproval)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoanService_ApproveLoan_Call) Return(err error) *LoanService_ApproveLoan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanService_ApproveLoan_Call) RunAndReturn(run func(ctx context.Context, loanID int, approvalData *models.LoanApproval) error) *LoanService_ApproveLoan_Call {
	_c.Call.Return(run)
	return _c
}

// CanTransitionToState provides a mock function for the type LoanService
func (_mock *LoanService) CanTransitionToState(ctx context.Context, loanID int, newState string) (bool, error) {
	ret := _mock.Called(ctx, loanID, newState)

	if len(ret) == 0 {
		panic("no return value specified for CanTransitionToState")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (bool, error)); ok {
		return returnFunc(ctx, loanID, newState)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) bool); ok {
		r0 = returnFunc(ctx, loanID, newState)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, loanID, newState)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanService_CanTransitionToState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanTransitionToState'
type LoanService_CanTransitionToState_Call struct {
	*mock.Call
}

// CanTransitionToState is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
//   - newState string
func (_e *LoanService_Expecter) CanTransitionToState(ctx interface{}, loanID interface{}, newState interface{}) *LoanService_CanTransitionToState_Call {
	return &LoanService_CanTransitionToState_Call{Call: _e.mock.On("CanTransitionToState", ctx, loanID, newState)}
}

func (_c *LoanService_CanTransitionToState_Call) Run(run func(ctx context.Context, loanID int, newState string)) *LoanService_CanTransitionToState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoanService_CanTransitionToState_Call) Return(b bool, err error) *LoanService_CanTransitionToState_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *LoanService_CanTransitionToState_Call) RunAndReturn(run func(ctx context.Context, loanID int, newState string) (bool, error)) *LoanService_CanTransitionToState_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLoan provides a mock function for the type LoanService
func (_mock *LoanService) CreateLoan(ctx context.Context, loan *models.Loan) error {
	ret := _mock.Called(ctx, loan)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Loan) error); ok {
		r0 = returnFunc(ctx, loan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanService_CreateLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLoan'
type LoanService_CreateLoan_Call struct {
	*mock.Call
}

// CreateLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - loan *models.Loan
func (_e *LoanService_Expecter) CreateLoan(ctx interface{}, loan interface{}) *LoanService_CreateLoan_Call {
	return &LoanService_CreateLoan_Call{Call: _e.mock.On("CreateLoan", ctx, loan)}
}

func (_c *LoanService_CreateLoan_Call) Run(run func(ctx context.Context, loan *models.Loan)) *LoanService_CreateLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Loan
		if args[1] != nil {
			arg1 = args[1].(*models.Loan)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanService_CreateLoan_Call) Return(err error) *LoanService_CreateLoan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanService_CreateLoan_Call) RunAndReturn(run func(ctx context.Context, loan *models.Loan) error) *LoanService_CreateLoan_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLoan provides a mock function for the type LoanService
func (_mock *LoanService) DeleteLoan(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLoan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanService_DeleteLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLoan'
type LoanService_DeleteLoan_Call struct {
	*mock.Call
}

// DeleteLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanService_Expecter) DeleteLoan(ctx interface{}, id interface{}) *LoanService_DeleteLoan_Call {
	return &LoanService_DeleteLoan_Call{Call: _e.mock.On("DeleteLoan", ctx, id)}
}

func (_c *LoanService_DeleteLoan_Call) Run(run func(ctx context.Context, id int)) *LoanService_DeleteLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanService_DeleteLoan_Call) Return(err error) *LoanService_DeleteLoan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanService_DeleteLoan_Call) RunAndReturn(run func(ctx context.Context, id int) error) *LoanService_DeleteLoan_Call {
	_c.Call.Return(run)
	return _c
}

// DisburseLoan provides a mock function for the type LoanService
func (_mock *LoanService) DisburseLoan(ctx context.Context, loanID int, disbursementData *models.LoanDisbursement) error {
	ret := _mock.Called(ctx, loanID, disbursementData)

	if len(ret) == 0 {
		panic("no return value specified for DisburseLoan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.LoanDisbursement) error); ok {
		r0 = returnFunc(ctx, loanID, disbursementData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanService_DisburseLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisburseLoan'
type LoanService_DisburseLoan_Call struct {
	*mock.Call
}

// DisburseLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
//   - disbursementData *models.LoanDisbursement
func (_e *LoanService_Expecter) DisburseLoan(ctx interface{}, loanID interface{}, disbursementData interface{}) *LoanService_DisburseLoan_Call {
	return &LoanService_DisburseLoan_Call{Call: _e.mock.On("DisburseLoan", ctx, loanID, disbursementData)}
}

func (_c *LoanService_DisburseLoan_Call) Run(run func(ctx context.Context, loanID int, disbursementData *models.LoanDisbursement)) *LoanService_DisburseLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.LoanDisbursement
		if args[2] != nil {
			arg2 = args[2].(*models.LoanDisbursement)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoanService_DisburseLoan_Call) Return(err error) *LoanService_DisburseLoan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanService_DisburseLoan_Call) RunAndReturn(run func(ctx context.Context, loanID int, disbursementData *models.LoanDisbursement) error) *LoanService_DisburseLoan_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoanByID provides a mock function for the type LoanService
func (_mock *LoanService) GetLoanByID(ctx context.Context, id int) (*models.Loan, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanByID")
	}

	var r0 *models.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Loan, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Loan); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanService_GetLoanByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoanByID'
type LoanService_GetLoanByID_Call struct {
	*mock.Call
}

// GetLoanByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *LoanService_Expecter) GetLoanByID(ctx interface{}, id interface{}) *LoanService_GetLoanByID_Call {
	return &LoanService_GetLoanByID_Call{Call: _e.mock.On("GetLoanByID", ctx, id)}
}

func (_c *LoanService_GetLoanByID_Call) Run(run func(ctx context.Context, id int)) *LoanService_GetLoanByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanService_GetLoanByID_Call) Return(loan *models.Loan, err error) *LoanService_GetLoanByID_Call {
	_c.Call.Return(loan, err)
	return _c
}

func (_c *LoanService_GetLoanByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Loan, error)) *LoanService_GetLoanByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoanByLoanID provides a mock function for the type LoanService
func (_mock *LoanService) GetLoanByLoanID(ctx context.Context, loanID string) (*models.Loan, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanByLoanID")
	}

	var r0 *models.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Loan, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Loan); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanService_GetLoanByLoanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoanByLoanID'
type LoanService_GetLoanByLoanID_Call struct {
	*mock.Call
}

// GetLoanByLoanID is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID string
func (_e *LoanService_Expecter) GetLoanByLoanID(ctx interface{}, loanID interface{}) *LoanService_GetLoanByLoanID_Call {
	return &LoanService_GetLoanByLoanID_Call{Call: _e.mock.On("GetLoanByLoanID", ctx, loanID)}
}

func (_c *LoanService_GetLoanByLoanID_Call) Run(run func(ctx context.Context, loanID string)) *LoanService_GetLoanByLoanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanService_GetLoanByLoanID_Call) Return(loan *models.Loan, err error) *LoanService_GetLoanByLoanID_Call {
	_c.Call.Return(loan, err)
	return _c
}

func (_c *LoanService_GetLoanByLoanID_Call) RunAndReturn(run func(ctx context.Context, loanID string) (*models.Loan, error)) *LoanService_GetLoanByLoanID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoansByState provides a mock function for the type LoanService
func (_mock *LoanService) GetLoansByState(ctx context.Context, state string) ([]*models.Loan, error) {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for GetLoansByState")
	}

	var r0 []*models.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.Loan, error)); ok {
		return returnFunc(ctx, state)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.Loan); ok {
		r0 = returnFunc(ctx, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanService_GetLoansByState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoansByState'
type LoanService_GetLoansByState_Call struct {
	*mock.Call
}

// GetLoansByState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *LoanService_Expecter) GetLoansByState(ctx interface{}, state interface{}) *LoanService_GetLoansByState_Call {
	return &LoanService_GetLoansByState_Call{Call: _e.mock.On("GetLoansByState", ctx, state)}
}

func (_c *LoanService_GetLoansByState_Call) Run(run func(ctx context.Context, state string)) *LoanService_GetLoansByState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanService_GetLoansByState_Call) Return(loans []*models.Loan, err error) *LoanService_GetLoansByState_Call {
	_c.Call.Return(loans, err)
	return _c
}

func (_c *LoanService_GetLoansByState_Call) RunAndReturn(run func(ctx context.Context, state string) ([]*models.Loan, error)) *LoanService_GetLoansByState_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalInvestedAmount provides a mock function for the type LoanService
func (_mock *LoanService) GetTotalInvestedAmount(ctx context.Context, loanID int) (float64, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalInvestedAmount")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (float64, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) float64); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanService_GetTotalInvestedAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalInvestedAmount'
type LoanService_GetTotalInvestedAmount_Call struct {
	*mock.Call
}

// GetTotalInvestedAmount is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
func (_e *LoanService_Expecter) GetTotalInvestedAmount(ctx interface{}, loanID interface{}) *LoanService_GetTotalInvestedAmount_Call {
	return &LoanService_GetTotalInvestedAmount_Call{Call: _e.mock.On("GetTotalInvestedAmount", ctx, loanID)}
}

func (_c *LoanService_GetTotalInvestedAmount_Call) Run(run func(ctx context.Context, loanID int)) *LoanService_GetTotalInvestedAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoanService_GetTotalInvestedAmount_Call) Return(f float64, err error) *LoanService_GetTotalInvestedAmount_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *LoanService_GetTotalInvestedAmount_Call) RunAndReturn(run func(ctx context.Context, loanID int) (float64, error)) *LoanService_GetTotalInvestedAmount_Call {
	_c.Call.Return(run)
	return _c
}

// InvestInLoan provides a mock function for the type LoanService
func (_mock *LoanService) InvestInLoan(ctx context.Context, loanID int, investment *models.LoanInvestment) error {
	ret := _mock.Called(ctx, loanID, investment)

	if len(ret) == 0 {
		panic("no return value specified for InvestInLoan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.LoanInvestment) error); ok {
		r0 = returnFunc(ctx, loanID, investment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanService_InvestInLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvestInLoan'
type LoanService_InvestInLoan_Call struct {
	*mock.Call
}

// InvestInLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID int
//   - investment *models.LoanInvestment
func (_e *LoanService_Expecter) InvestInLoan(ctx interface{}, loanID interface{}, investment interface{}) *LoanService_InvestInLoan_Call {
	return &LoanService_InvestInLoan_Call{Call: _e.mock.On("InvestInLoan", ctx, loanID, investment)}
}

func (_c *LoanService_InvestInLoan_Call) Run(run func(ctx context.Context, loanID int, investment *models.LoanInvestment)) *LoanService_InvestInLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.LoanInvestment
		if args[2] != nil {
			arg2 = args[2].(*models.LoanInvestment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoanService_InvestInLoan_Call) Return(err error) *LoanService_InvestInLoan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanService_InvestInLoan_Call) RunAndReturn(run func(ctx context.Context, loanID int, investment *models.LoanInvestment) error) *LoanService_InvestInLoan_Call {
	_c.Call.Return(run)
	return _c
}

// ListLoans provides a mock function for the type LoanService
func (_mock *LoanService) ListLoans(ctx context.Context, state *string, offset int, limit int) ([]*models.Loan, error) {
	ret := _mock.Called(ctx, state, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListLoans")
	}

	var r0 []*models.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int, int) ([]*models.Loan, error)); ok {
		return returnFunc(ctx, state, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int, int) []*models.Loan); ok {
		r0 = returnFunc(ctx, state, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, int, int) error); ok {
		r1 = returnFunc(ctx, state, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LoanService_ListLoans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLoans'
type LoanService_ListLoans_Call struct {
	*mock.Call
}

// ListLoans is a helper method to define mock.On call
//   - ctx context.Context
//   - state *string
//   - offset int
//   - limit int
func (_e *LoanService_Expecter) ListLoans(ctx interface{}, state interface{}, offset interface{}, limit interface{}) *LoanService_ListLoans_Call {
	return &LoanService_ListLoans_Call{Call: _e.mock.On("ListLoans", ctx, state, offset, limit)}
}

func (_c *LoanService_ListLoans_Call) Run(run func(ctx context.Context, state *string, offset int, limit int)) *LoanService_ListLoans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *LoanService_ListLoans_Call) Return(loans []*models.Loan, err error) *LoanService_ListLoans_Call {
	_c.Call.Return(loans, err)
	return _c
}

func (_c *LoanService_ListLoans_Call) RunAndReturn(run func(ctx context.Context, state *string, offset int, limit int) ([]*models.Loan, error)) *LoanService_ListLoans_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLoan provides a mock function for the type LoanService
func (_mock *LoanService) UpdateLoan(ctx context.Context, id int, loan *models.Loan) error {
	ret := _mock.Called(ctx, id, loan)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLoan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.Loan) error); ok {
		r0 = returnFunc(ctx, id, loan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoanService_UpdateLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLoan'
type LoanService_UpdateLoan_Call struct {
	*mock.Call
}

// UpdateLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - loan *models.Loan
func (_e *LoanService_Expecter) UpdateLoan(ctx interface{}, id interface{}, loan interface{}) *LoanService_UpdateLoan_Call {
	return &LoanService_UpdateLoan_Call{Call: _e.mock.On("UpdateLoan", ctx, id, loan)}
}

func (_c *LoanService_UpdateLoan_Call) Run(run func(ctx context.Context, id int, loan *models.Loan)) *LoanService_UpdateLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.Loan
		if args[2] != nil {
			arg2 = args[2].(*models.Loan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LoanService_UpdateLoan_Call) Return(err error) *LoanService_UpdateLoan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoanService_UpdateLoan_Call) RunAndReturn(run func(ctx context.Context, id int, loan *models.Loan) error) *LoanService_UpdateLoan_Call {
	_c.Call.Return(run)
	return _c
}
